# Generated by Django 4.2.1 on 2023-08-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgmodel',
            name='ex_class',
            field=models.IntegerField(),
        ),
    ]
