# Generated by Django 4.2.1 on 2023-08-21 08:43

from django.db import migrations, models
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_data', django_base64field.fields.Base64Field(blank=True, default='', max_length=900000, null=True)),
                ('ex_class', models.IntegerField(max_length=10)),
                ('ex_name', models.CharField(max_length=50)),
            ],
        ),
    ]
