# Generated by Django 4.2.1 on 2023-08-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_imgmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_name', models.CharField(blank=True, max_length=100)),
                ('ex_part', models.CharField(blank=True, max_length=50)),
                ('ex_method', models.TextField()),
            ],
        ),
    ]
